### PR TITLE
Brought python 3 compatibility

### PR DESCRIPTION
**Pull request by KOLANICH**
With 2to3 and manual fixes. Some fixes with six may be needed. But do it yourself: I don't have python 2 on my machines.

### CODE REVIEW

**Comment by Storyyeller** [comment]
What is the point of this? The assembler and disassembler already support Python 3, while the decompiler is too big and complex to be worth the effort of porting. I suppose it could be useful to have this PR available in case people want to run the decompiler under Python 3 as well, but I don't see it ever being merged. I don't trust 2to3 to not break things, and I don't want to uglify the code so much either.

**Comment by KOLANICH** [comment]
>The assembler and disassembler already support Python 3, while the decompiler is too big and complex to be worth the effort of porting.

It's already ported. And it works. Other decompilers (luyten, jd) have failed to decompile the code.

>I don't trust 2to3 to not break things, and I don't want to uglify the code so much either.

I have reviewed it changes manually and fixed what I found it had spoiled.

**Comment by z3ntu** [comment]
@Storyyeller Python 2 will be EOL in 2020 and several distributions are already planning to drop Python 2. If you want your software to stay compatible you should try to port it over (or let other people do it :wink: )

**Comment by KOLANICH** [comment]
>or let other people do it 😉

Who doesn't let? If you are ready to merge python3 port with the @Storyyeller 's repo, just create an org and clone my repo there. I guess merging would be easier if a one uses some better merge tool working on AST level.

>Python 2 will be EOL in 2020

I'd prefer it to be EOL in 2010.

**Comment by z3ntu** [comment]
> I'd prefer it to be EOL in 2010.

Well it was planned to be in 2015 but people complained ¯\\\_(ツ)\_/¯

**Comment by KOLANICH** [comment]
@Storyyeller, python 2 is already long EOL. Maybe this PR should be reopened and merged?

**Comment by Storyyeller** [comment]
The main issue is the maintenance burden. The reason I didn't try to port the decompiler to python 3 before is because there's a high risk of breakages and I didn't have the time and energy to go through and try to find them all.

**Comment by KOLANICH** [comment]
>is because there's a high risk of breakages and I didn't have the time and energy to go through and try to find them all.

Python 3 is not so different to python 2 to get a lot of breakages. BTW I use python 3 from 2013, and Krakatau since I have ported it. Works OK for me.

Do you have a test suite for decompilation?

>In any case, just because Python 2 is EOL doesn't mean people aren't still using it.

Yes, and neither just because it exists people are wiling to ha e it on their machines. I have never used 2 as the main interpreter, in fact I only used 2 (not counting the software bundled with 2 here) to test some projects I had to contribute that required compatibility to 2.  Anyway, I see no reason to use 2 while 3 is much better.

**Comment by Storyyeller** [comment]
There are tests for the decompiler, but coverage is not great.

**Pull request closed without merging**
